version: "3.7"

services:
  web:
    build: ./projects
    command: gunicorn auction.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./projects/:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
