# Generated by Django 3.0.7 on 2020-10-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201013_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='avtor',
            new_name='author',
        ),
    ]
