# Generated by Django 3.0.7 on 2020-10-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201013_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
    ]
